apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-notebook-data00
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /data/nfs/jupyter/data00
    server: nfs.example.com
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
